### PR TITLE
Update deep merge() to work with an array argument

### PR DESCRIPTION
**Pull request by lelandmiller**
Had to pull these changes to a branch in my fork to avoid editing history of master. This should be the same as #140, which I will close out.

### CODE REVIEW

**Comment by lelandmiller** [comment]
Sorry for the slow response @rtfeldman. Fixed the merge conflicts, looks like the failure of CI is still due to missing saucelabs credentials.

**Comment by rtfeldman** [comment]
Great, thank you @lelandmiller!

**Comment by rtfeldman** [comment]
Released as 6.1.4! 🎉

**Comment by lelandmiller** [comment]
Thank you!

**Pull request merged**
