### PR TITLE
Update deep merge() to work with an array argument

### PR DESCRIPTION
**Pull request by lelandmiller**
Maybe I am misunderstanding how this should work. I was expecting a deep merge to deeply merge each object in an array sequentially. The behavior I expected is what I added a test for. Please let me know if I am misinterpreting the API, I can fix this in another way if you would like as well.

### CODE REVIEW

**Comment by lelandmiller** [comment]
Looks like the build failed to a credentials issue, not test failures:

```
Zuul tried to run tests in saucelabs, however no saucelabs credentials were provided.
```

**Comment by lelandmiller** [comment]
Just wanted to ping on this and see if anyone had any feedback.

Thanks :-)

**Comment by crudh** [comment]
@lelandmiller looks like a bug and a legit fix to me! @rtfeldman ?

**Comment by lelandmiller** [comment]
Hey, @rtfeldman! just wanted to check in on this again to see if there is anything I could do to possibly get this in a published version of seamless-immutable.

Thanks!

**Comment by rtfeldman** [comment]
@lelandmiller really sorry I took so long getting to this! Looks good to me.

If you can resolve the merge conflicts I'll merge and publish this.

**Comment by lelandmiller** [comment]
Closing and continuing on #156.

**Pull request closed without merging**
