### PR TITLE
Handle promises

### LINKED ISSUE #153: issue while working with Promise
```
const names = [{name: "Bob"}, {name: "Foo"}];
console.log("names:" + JSON.stringify(names));

Promise.all(
    names.map(n => {
        return Promise.resolve(n).then(n => {
            console.log("n:" + JSON.stringify(n));
            return n;
        })
    })
).then(namesBack => {
    console.log("namesBack:" + JSON.stringify(namesBack));
});
```

The code above results in this:

> names:[{"name":"Bob"},{"name":"Foo"}]
> n:{"name":"Bob"}
> n:{"name":"Foo"}
> namesBack:[{"name":"Bob"},{"name":"Foo"}]

However If you only change the first line to use immutable like this: 

```
const names = Immutable.from([{name: "Bob"}, {name: "Foo"}]);
console.log("names:" + JSON.stringify(names));

Promise.all(
    names.map(n => {
        return Promise.resolve(n).then(n => {
            console.log("n:" + JSON.stringify(n));
            return n;
        })
    })
).then(namesBack => {
    console.log("namesBack:" + JSON.stringify(namesBack));
});
```

The result differs:

> names:[{"name":"Bob"},{"name":"Foo"}]
> n:{"name":"Bob"}
> n:{"name":"Foo"}
> namesBack:[{"_45":0,"_81":0,"_65":null,"_54":null},{"_45":0,"_81":0,"_65":null,"_54":null}]

If we call asMutable() before .map call, then we are fine:

```
const names = Immutable.from([{name: "Bob"}, {name: "Foo"}]);
console.log("names:" + JSON.stringify(names));

Promise.all(
    names.asMutable().map(n => {
        return Promise.resolve(n).then(n => {
            console.log("n:" + JSON.stringify(n));
            return n;
        })
    })
).then(namesBack => {
    console.log("namesBack:" + JSON.stringify(namesBack));
});
```

result:

> names:[{"name":"Bob"},{"name":"Foo"}]
> n:{"name":"Bob"}
> n:{"name":"Foo"}
> namesBack:[{"name":"Bob"},{"name":"Foo"}]

We have no intent to mutate anything, so there should not be a need to call **asMutable**. 
An enhancement to the "seamless-immutable" would be good.

### PR DESCRIPTION
**Pull request by dentrado**
Don’t make promises immutable, but make their fulfillment value immutable.
Fixes #153

### CODE REVIEW

**Comment by rtfeldman** [comment]
@dentrado Thanks! Would you mind adding a test to cover the behavior of rejected promise values?

Also, no need to check in the built files; I'll do that before publishing the next release. 🙂

**Comment by dentrado** [comment]
@rtfeldman sure, I've added an additional test now.

**Comment by dhirendrarathod2000** [comment]
@dentrado @rtfeldman\
Any ETA when it will be released?

**Comment by rtfeldman** [comment]
Out now! `7.1.0`

**Pull request merged**
