### PR TITLE
Immutable arrays creation works with modified Array.prototype

### PR DESCRIPTION
**Pull request by mkawalec**
I use an evil library that adds a method to Array.prototype. Without this fix `seamless-immutable` tries to both add this new method as immutable and banned properties, exploding in the meantime.

### CODE REVIEW

**Comment by rtfeldman** [comment]
Interesting! Would you mind adding a test case that evilly adds a method to Array.prototype and no longer explodes?

**Comment by rtfeldman** [comment]
Also, you can just run `grunt` to rebuild both the development and production builds automatically.

**Comment by mkawalec** [comment]
@rtfeldman done, and thanks for letting me know, in case I find any other bugs :dancers:

**Comment by rtfeldman** [comment]
Awesome - thanks for the fix!

**Comment by rtfeldman** [comment]
This is now released in [version 2.4.1](https://www.npmjs.com/package/seamless-immutable)

**Pull request merged**
