### PR TITLE
Special handling of dates

### LINKED ISSUE #24: breaks on a date
Example:

```js
var Immutable = require('seamless-immutable');
var d = { date: new Date() };
console.log(d.date.toISOString());
var d = Immutable(d);
console.log(d.date.toISOString());
```

Console:

```
2015-03-18T03:17:29.895Z
/Users/matt/Playground/seamless-immutable/index.js:5
console.log(d.date.toISOString());
                   ^
TypeError: undefined is not a function
    at Object.<anonymous> (/Users/matt/Playground/seamless-immutable/index.js:5:20)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

### PR DESCRIPTION
**Pull request by crudh**
Added special handling of dates instead of converting them to regular objects.
This is the result of the discussion in issue #25 that was created due to issue #24.

Also made sure we don't try to deep merge dates.

This fixes #24.

### CODE REVIEW

**Comment by rtfeldman** [comment]
Looks great! Nice and straightforward.

**Comment by rtfeldman** [comment]
Looks like there are some cross-browser test failures: https://travis-ci.org/#L600

Possibly `new Date(dateObject)` doesn't pass through time zone in all browsers?

**Comment by crudh** [comment]
@rtfeldman: Seems like it! Replacing the `.toISOString()` comparisons with `.getTime()` comparisons should solve the problem. You want me to add it to the current PR, a new one or do you want to do it yourself?

**Comment by rtfeldman** [comment]
If you don't mind, a new PR would be great. :smiley:

**Comment by rtfeldman** [comment]
Seems it's not just `.toISOString()`! IE now reports different `.getTime()` numbers: https://travis-ci.org/rtfeldman/seamless-immutable#L616

Maybe using a different constructor is in order?

**Comment by crudh** [comment]
I just got access to an IE11 and tested it (and in a Firefox) and saw the problem with using the constructor:
`new Date(originalDate)`.

But the following works in both:
`new Date(originalDate.getTime())`.

I have seen a lot of examples doing it the first way and as far as I understood it should then use the `.valueOf` method on the date which generates the same output as `.getTime` in all browsers. So not sure why the first way fails, but I will change it to the second way.

Thanks for the suggestion @rtfeldman. A PR is coming, sorry for the mess.

**Comment by crudh** [comment]
The constructor `new Date(originalDate)` throws away the millseconds in some browsers (IE, FF) but not other (Chrome, others?).

Using `new Date(originalDate.getTime())` preserves the milliseconds. This is fixed in PR #33.

**Pull request merged**
