### PR TITLE
Add "react-native" key to package.json

### LINKED ISSUE #180: v7.0.0 seems broken in React Native environment
Just upgraded from 6.1.1, causing import error.

### PR DESCRIPTION
**Pull request by jgkim**
This resolves #180, which is related to facebook/react-native#2208.

### CODE REVIEW

**Comment by rtfeldman** [comment]
Thanks!

However, I don't understand why the source works but the development build fails. I'd like to understand this fix better before applying it...what is it about the development build that react native rejects it?

**Comment by jgkim** [comment]
@rtfeldman Since the build files for broswers are listed in `.npmignore`, it cannot be imported in the `react-native` environment.

**Comment by rtfeldman** [comment]
@jgkim ah, got it!

In that case, it seems like it would make more sense to fix this by removing these from `.npmignore`:

```
seamless-immutable.development.min.js
seamless-immutable.development.js
seamless-immutable.production.min.js
```

...and then having both `react-native` and `browser` point to the development build.

What do you think?

**Comment by rtfeldman** [comment]
Yeah maybe `main` should be `node`?

I think since we know about `react-native` it makes sense to include it alongside `browser`, just to be explicit.

**Comment by jgkim** [comment]
Making it explicit is good. :) I think `react-native` is more similar to `node` rather than `browser`. The packager of `react-native` will transphile and minify the source. However, in which case, it will work. ;)

**Comment by rtfeldman** [comment]
@jgkim If you make those changes above, can you rebase on top of `master`? I pushed (what ought to be) a fix for Travis builds getting credentials errors on PRs.

**Comment by rtfeldman** [comment]
Thanks @jgkim!

**Pull request merged**
