### PR TITLE
FIX #76 Incompatible with Object.create(null)

### LINKED ISSUE #76: Incompatible with Object.create(null)
Hello. Thanks for seamless. It's a very nice piece of software.

I was surprised however that I cannot create immutable object from an object without prototype (e.g. acquired with `Object.create(null)`:

```javascript
Immutable(Object.create(null));
// TypeError: target.hasOwnProperty is not a function
```

It is also impossible to merge such an object into `immutable`:

```javascript
var o1 = Immutable({a: 1});
var o2 = Object.create(null);
o2.b = 2;
o1.merge(o2);
// TypeError: other.hasOwnProperty is not a function
```

Obviously it depends on `hasOwnProperty` method of the original object, which is usually available in a prototype chain.

Can we use global `Object` methods instead, like `Object.getOwnPropertyDescriptor`? I'll be happy to provide PR, but would like to discuss it first.

### PR DESCRIPTION
**Pull request by lzrski**
Changed all invocations of `<obj>.hasOwnProperty(<key>)` to `Object.hasOwnProperty.call(<obj>, <key>)`, unless I was certain that <obj> is instance of `Immutable` or `Array`.

Unfortunately I did not provide any test cases for the compatibility with *prototypeless* objects. Any help here would be appreciated. Sorry, but the setup of test suit is quite sophisticated and I had only limited time to work on that.

I have tested it manually and it seems to work. Lack of real unit tests is the reason for question mark in commit message title.

All existing tests are passing in my local environment.

#76

### CODE REVIEW

**Comment by lzrski** [comment]
The CI build is still failing, this time when trying to run Zuul tests. Is there anything I can do about it?

**Comment by rtfeldman** [comment]
Hm, this would be a performance regression given that [call and apply are significantly slower than direct invocation](http://stackoverflow.com/questions/8184466/why-are-call-and-apply-slower-than-a-direct-function-call-in-javascript).

Was there a reason the `Object.getOwnPropertyDescriptor` approach discussed in #76 wouldn't work?

**Comment by lzrski** [comment]
@rtfeldman no, not really. I guess I was too lazy to read my own issue.

Should be better now.

**Comment by rtfeldman** [comment]
@lzrski hm, looks like build fails on Android: https://travis-ci.org/rtfeldman/seamless-immutable

**Comment by lzrski** [comment]
I did some research and actually the complete list of platforms that are failing is:

1.  android 4.0 on Linux
2.  android 5.1 on Linux
3.  internet explorer 10 on Windows 2012
4.  internet explorer 11 on Windows 10
5.  internet explorer 9 on Windows 2008
6.  opera 12 on Windows 2003
7.  safari 6 on Mac 10.8

They all fail at the same two tests:

1.  [ImmutableArray :: #asMutable :: returns a deep mutable copy if provided the deep flag][test array]
2.  [ImmutableObject :: #asMutable :: returns a deep mutable copy if provided the deep flag][test object]

The errors are:

|Platform  | Error                                                            |
|----------|------------------------------------------------------------------|
|IE        | Object.getOwnPropertyDescriptor: argument is not an Object       |
|Safari    | Requested property descriptor of a value that is not an object.  |
|Opera     | Object.getOwnPropertyDescriptor: first argument not an Object    |
|Android   | Object.getOwnPropertyDescriptor called on non-object             |

Which practically boils down to the same thing.

**Why**

According to [ES 5.1 standard][ES5] if first argument to `Object.getOwnPropertyDescriptor` is not an `Object` it throws a `TypeError` exception. That's what we get in failing platforms.

According to [ES 2015 standard][ES6] the first argument is always coerced to object.

All failing platforms seem to behave according to ES 5 standard. In our case the function causing the errors is [asDeepMutable][], which just passes whatever it gets to `Object.getOwnPropertyDescriptor`. It is being called by two other functions [asMutableArray][] and [asMutableObject][]. Both iterate indiscriminately over elements / keys and pass them to `asDeepMutable`. So when the value is not an object (e.g. a `number`, `null`, etc.) the ES 5 platforms are throwing errors.

The solution is probably to check the type of argument passed to `asDeepMutable`.

PR comming soon :)

[test array]: https://github.com/rtfeldman/seamless-immutable/blob/de08878211be3fac6cc29b9d372cee7145489e67/test/ImmutableArray/test-asMutable.js#L37
[test object]: https://github.com/rtfeldman/seamless-immutable/blob/de08878211be3fac6cc29b9d372cee7145489e67/test/ImmutableObject/test-asMutable.js#L37
[ES5]: http://www.ecma-international.org/ecma-262/5.1/#sec-15.2.3.3
[ES6]: http://www.ecma-international.org/ecma-262/6.0/#sec-object.getownpropertydescriptor
[asMutableArray]: https://github.com/rtfeldman/seamless-immutable/blob/de08878211be3fac6cc29b9d372cee7145489e67/src/seamless-immutable.js#L242
[asMutableObject]: https://github.com/rtfeldman/seamless-immutable/blob/de08878211be3fac6cc29b9d372cee7145489e67/src/seamless-immutable.js#L434
[asDeepMutable]: https://github.com/rtfeldman/seamless-immutable/blob/de08878211be3fac6cc29b9d372cee7145489e67/src/seamless-immutable.js#L283

**Pull request merged**
