### PR TITLE
Ensure object is an Immutable before calling merge on it

### PR DESCRIPTION
**Pull request by tiil**
Different approach to solve merge() getting called on empty objects. Passes tests this time. Ping @rtfeldman.

### CODE REVIEW

**Comment by rtfeldman** [comment]
@tiil I'm surprised this approach fixes https://github.com/rtfeldman/seamless-immutable/issues/82 - would you mind adding a test case to confirm that it's fixed?

**Comment by tiil** [comment]
@rtfeldman Sorry for not being responsive. This PR merely works around #82 by always turning currentValue into an Immutable before calling merge on it - it's not pretty but it doesn't break any tests unlike the previous attempt. I'll try to provide a test case soon.

**Comment by rtfeldman** [comment]
Thanks! :smiley:

**Comment by davidkpiano** [comment]
Extremely tiny nit: isMerg**e**ableObject :wink:

**Comment by rtfeldman** [comment]
Closing as stale; feel free to reopen if desired!

**Pull request closed without merging**
