### PR TITLE
Production mode and Grunt build process

### LINKED ISSUE #6: Prod Mode
In production, it's probably unnecessary to actually freeze objects and throw exceptions when mutating methods are invoked. Those are mainly necessary in development, but by the time the code hits production, if any invariants aren't being followed, you should already know about it.

With that in mind, having a way to turn off the freezing and overriding should speed up performance, particularly in Safari. Adding a quick flag to turn this on would be useful to that end.

### PR DESCRIPTION
**Pull request by crudh**
This PR includes a build process using Grunt that envifies seamless-immutable.js to two output files: one for development and one for production. The production file is also uglyfied.

seamless-immutable.js has been moved to the src folder and the freezing of objects and banning of properties will only be performed when using the development output file.

I also updated all tests and everything in package.json to use the development file instead of the main source file.

I have NOT added and commited the two output files yet, that should be done immediately after merge since they are expected to be there.

This fixes #6.

### CODE REVIEW

**Comment by crudh** [comment]
The last commit message should read: "Only freeze and ban properties if in **dev** mode."

**Comment by rtfeldman** [comment]
Looks great!

Only one request: it should be pretty easy to parameterize the tests such that they check both the dev and the prod builds...something like this:

```javascript
[
  {buildName: "development build", src: "../../seamless-immutable.development.js"},
  {buildName: "production build",  src: "../../seamless-immutable.production.min.js"}
].forEach(function(config) {
  var Immutable = require(config.src);

  // ...other requires go here

  describe(config.buildName, function() {

    // ...all the current tests go here

  });
});
```

Thanks a ton for doing this! Really excellent work. :smiley_cat:

**Comment by crudh** [comment]
Now all tests are run for both the development build and the production build. There are a few exceptions, like checking if the object is frozen, where we only run it for one build. But then I have added a simple test for the other build too.

I only placed the build config in the *.spec.js files. Then I passed the config into the test functions in ImmutableObject/* and ImmutableArray/* so they could require in the correct Immutable build.

I had to do some changes to TestUtil so that it uses the correct Immutable build depending on the config. Basically instead of exporting an object it exports a function that takes the chosen Immutable and returns an object with functions that uses the correct Immutable. This seemed like the cleanest way to do it, but I'm open to suggestions :smile:

**Comment by rtfeldman** [comment]
This is fantastic! Love it. :heart_eyes_cat: 

That approach with `TestUtil` seems totally fine.

**Pull request merged**
