### PR TITLE
Updated way of cloning dates

### PR DESCRIPTION
**Pull request by crudh**
This should fix the way dates are cloned, that was introduced in #31.

### CODE REVIEW

**Comment by crudh** [comment]
Tested, and it works, in latest Chrome, Firefox and IE.

**Comment by crudh** [comment]
Remember to do a grunt build after merge to generate the new prod and dev files.

**Comment by rtfeldman** [comment]
Yep! Want to make sure the build is green before I bump the version to 2.3.1 and do a prod build. :smiley:

**Comment by crudh** [comment]
@rtfeldman: Ok! But will Travis run Grunt to generate the new prod/dev files? If it uses the current commited ones in master the tests will continue to fail.

**Comment by rtfeldman** [comment]
Ah, good point! No it won't. Updated in 1ccdc276875ef3b09ac2e1071dc7a907e17fa7f9

**Comment by rtfeldman** [comment]
All set! :+1: 

Thanks for the fixes!

**Pull request merged**
