### PR TITLE
Implement .without(predicate) - see #87

### PR DESCRIPTION
**Pull request by jakubholynet**
Exclude all keys/values that satisfy the predicate

Simplify the test by testing primarily 
without(predicate).

PS: I recommend to also run `git co e09e798 test/ImmutableObject/test-without.js; grunt`
to verify that the old tests before my refactoring still pass (they do for me but you should
not trust me :-))

### CODE REVIEW

**Comment by rtfeldman** [comment]
Old tests pass for me too.

Looks great, thanks!

**Comment by jakubholynet** [comment]
My pleasure

**Comment by rtfeldman** [comment]
@jakubholynet Hm, appears that tests are breaking in Firefox. I fixed some linter errors in the hopes that's all it was, but it appears to be more than that.

Mind taking a look?

**Comment by jakubholynet** [comment]
Yes. How to run the tests in FF?

**Comment by jakubholynet** [comment]
Hi @rtfeldman, as mentioned I'd be happy to help with the failing tests but I need you to tell me how to run them :-)

**Comment by rtfeldman** [comment]
@jakubholynet They are still broken, as far as I can tell. If you run `npm run zuul-local` and then visit the address printed to the console in Firefox, it will run the tests!

**Comment by jakubholynet** [comment]
the pass for me:

seamless-immutable

**Comment by rtfeldman** [comment]
Ended up getting things fixed. Thanks for the PR! :smile_cat:

**Pull request merged**
