### PR TITLE
use isArray when type checking

### LINKED ISSUE #146: Array is treated as object in certain setup
It happens only on one of my computers and I could not understand why but Immutable fails to detect arrays as such and treats them like regular objects.

The simple reconstruction:
```
Immutable = require('seamless-immutable')
Immutable([1,2,3])
//output is:
{ '0': 1, '1': 2, '2': 3 }
```

### PR DESCRIPTION
**Pull request by variant77**
This PR fixed #146 

I traced the problem to an erroneous return value of `instanceof Array` . for some reason in my setup it returns `false`. According to the MDN docs this [can happen in multiple context scenarios](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof#instanceof_and_multiple_context_(e.g._frames_or_windows)) and it is advised to use `Array.isArray` instead.

### CODE REVIEW

**Comment by variant77** [comment]
@rtfeldman I'd love to get your input on this PR

**Comment by rtfeldman** [comment]
Looks good! So sorry for the delay in merging this @variant77!

**Comment by brunolemos** [comment]
@rtfeldman please update the npm package :)

**Comment by rtfeldman** [comment]
Released as 6.1.2 @brunolemos @variant77

**Pull request merged**
