### PR TITLE
Add getIn function

### PR DESCRIPTION
**Pull request by dentrado**
This PR adds a `getIn` function as requested in #149.

### CODE REVIEW

**Comment by dentrado** [comment]
ping @rtfeldman

**Comment by rtfeldman** [comment]
Great, thank you @dentrado!

**Comment by hassanbazzi** [comment]
Any idea when this will be released?

**Comment by bm-axel** [comment]
So this hasn't been released yet? I just downloaded seamless-immutable for the first time today and saw Immutable.getIn in the readme and was surprised to find it not working!

**Comment by smashercosmo** [comment]
@rtfeldman Would it be possible to cut a release?

**Comment by geirsagberg** [comment]
Seems to be released now.

**Pull request merged**
